---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangkaituo.
--- DateTime: 2026/4/21 19:16
---
if(redis.call("get", KEYS[1]) == ARGV[1]) then
    redis.call("del", KEYS[1])
end
return 0